### ISSUE TITLE
1pt Setup front-end project 

### ISSUE THREAD

**Issue by silviatofana** [silviatofana/Doctor-appointment#1]
create the repository for Doctor appointment Front-End
add React and Redux
add linters configuration and .github/workflow/linters.yml

**Comment by Felix45** [comment]
The link below is a pull request that addresses this issue

[https://github.com/Felix45/Doctor-Appointment-Front-end/pull/1](https://github.com/Felix45/Doctor-Appointment-Front-end/pull/1l)
