### ISSUE TITLE
Final capstone  Kanban board setup  

### ISSUE THREAD

**Issue by silviatofana** [silviatofana/Doctor-appointment#20]
## Kanban board review request
In this capstone group, we are a team of three people namely @silviatofana , @henrycode460   and @Felix45 

## Kanban link
[Kanban board link >>](https://github.com/users/silviatofana/projects/10/views/1)

## Kanban board screenshot
![Screenshot from 2022-11-09 12-55-56](https://user-images.githubusercontent.com/16392046/200800710-44f92d20-ff51-4648-8825-a83110f704ff.png)

**Comment by Meltrust** [comment]
Hi @silviatofana,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Nice detailed board✔️ 
- All cards have points✔️ 
- Point distribution is fair✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by silviatofana** [comment]
Thanks
